name = "AtomicMiscellany"
uuid = "bc03fc7c-bde9-44d6-a7d2-c740425f0bb3"
authors = ["JuliaAtoms contributors"]
version = "0.1.0"

[deps]
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
GSL = "1"
PhysicalConstants = "0.2"
Roots = "1"
QuadGK = "2"
SpecialFunctions = "0.10, 1"
Unitful = "1"
julia = "1.3"

[extras]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "QuadGK"]
