name = "AtomicMiscellany"
uuid = "bc03fc7c-bde9-44d6-a7d2-c740425f0bb3"
authors = ["JuliaAtoms contributors"]
version = "0.1.0"

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
QuadGK = "2"
SpecialFunctions = "0.10, 1"
julia = "1.3"

[extras]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "QuadGK"]
